[build-system]
requires = ["setuptools>=42", "setuptools-git-versioning", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "alabos_project"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = []

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
