[general]
working_dir = "."
name = '__fake_alab__'

[mongodb]
host = 'localhost'
port = 27017
username = ''
password = ''

[mongodb_completed]
host = 'localhost'
port = 27017
username = ''
password = ''

[rabbitmq]
host = "localhost"
port = 5672

[versioning]
versioning_style = "git"